//reducerUsers
export const SEARCH_USERS_RESULTS = "SEARCH_USERS_RESULTS";
export const CLEAN_USERS_RESULTS = "CLEAN_USER_RESULTS"
//reducerRepoitories
export const SEARCH_REPOSITORIES_RESULTS = "SEARCH_REPOSITORIES_RESULTS";
export const CLEAN_REPOSITORIES_RESULTS = "CLEAN_REPOSITORIES_RESULTS"
//reducerRequest
export const LOADING = "LOADING";
export const ACTIVEMODE = "ACTIVEMODE"